### ISSUE TITLE
框架安装 导入sql 有个错误 

### ISSUE THREAD

**Issue by chinacase** [deatil/laket-admin#2]
laket-admin/src/Support/Sql.php 

117 :  return implode($pure_sql, "");   改成    return implode("",$pure_sql);

121:    $pure_sql = implode($pure_sql, "\n");   改成 $pure_sql = implode( "\n",$pure_sql);

**Comment by chinacase** [comment]
implode(): Passing glue string after array is deprecated. Swap the parameters

**Comment by chinacase** [comment]
error:  implode(): Passing glue string after array is deprecated. Swap the parameters

**Comment by deatil** [comment]
已修复
