### ISSUE TITLE
验证码一致输入错误

### ISSUE THREAD

**Issue by jinxu96** [deatil/laket-admin#5]
验证码一致输入错误

**Comment by deatil** [comment]
开一下debug看下具体的有没有报错

**Comment by jinxu96** [comment]
> 开一下debug看下具体的有没有报错

没有错误

**Comment by deatil** [comment]
验证码默认用的session，你先确认下session的目录权限对不对，单用session能不能用

**Comment by deatil** [comment]
登录页面源码看下 passkey 这个有没有数据。
报错的话有密码传递没对或者session没对

**Comment by jinxu96** [comment]
> 登录页面源码看下 passkey 这个有没有数据。 报错的话有密码传递没对或者session没对

创建验证码的方法没有看到有存入session

**Comment by deatil** [comment]
用的是官方的验证码库

**Comment by jinxu96** [comment]
> 用的是官方的验证码库

好的，在app目录下开发，需要怎么做

**Comment by deatil** [comment]
需要后台路由，就用这种 https://github.com/deatil/laket-admin-database/blob/main/resources/routes/admin.php#L10 ，其他的前台开发就正常的 thinkphp 开发就行

**Comment by jinxu96** [comment]
> 需要后台路由，就用这种 https://github.com/deatil/laket-admin-database/blob/main/resources/routes/admin.php#L10 ，其他的前台开发就正常的 thinkphp 开发就行

好，现在是账号密码错误

**Comment by deatil** [comment]
> > 需要后台路由，就用这种 https://github.com/deatil/laket-admin-database/blob/main/resources/routes/admin.php#L10 ，其他的前台开发就正常的 thinkphp 开发就行
> 
> 好，现在是账号密码错误

看下openssl扩展开启没有

**Comment by jinxu96** [comment]
> > > 需要后台路由，就用这种 https://github.com/deatil/laket-admin-database/blob/main/resources/routes/admin.php#L10 ，其他的前台开发就正常的 thinkphp 开发就行
> > 
> > 
> > 好，现在是账号密码错误
> 
> 看下openssl扩展开启没有

开了

**Comment by deatil** [comment]
重置下密码试下 php think laket-admin:reset-password

**Comment by jinxu96** [comment]
> 重置下密码试下 php think laket-admin:reset-password
好了，但是谷歌还是不行，换了火狐可以了

**Comment by deatil** [comment]
> > 重置下密码试下 php think laket-admin:reset-password
> > 好了，但是谷歌还是不行，换了火狐可以了

谷歌浏览器看下它控制台报什么错？谷歌该说问题不大

**Comment by deatil** [comment]
会不会有浏览器插件影响？

**Comment by jinxu96** [comment]
> 会不会有浏览器插件影响？

没插件，可能版本问题？

**Comment by deatil** [comment]
> 

> > 会不会有浏览器插件影响？
> 
> 没插件，可能版本问题？

说不准。谷歌浏览器用的哪个版本？我这谷歌浏览器内核的浏览器测试没有出现这种问题

**Comment by jinxu96** [comment]
> > 
> 
> > > 会不会有浏览器插件影响？
> > 
> > 
> > 没插件，可能版本问题？
> 
> 说不准。谷歌浏览器用的哪个版本？我这谷歌浏览器内核的浏览器测试没有出现这种问题

这个版本115.0.5790.110

**Comment by deatil** [comment]
看起来像是新版本浏览器的对cookie设置有变化。

**Comment by deatil** [comment]
有比对过正常的登录提交数据和不正常是数据是否一样

**Comment by jinxu96** [comment]
> 有比对过正常的登录提交数据和不正常是数据是否一样
没纠结这个了，换浏览器
