### ISSUE TITLE
驱动程序 [Think] 不受支持

### ISSUE THREAD

**Issue by vpscn2gmail** [deatil/laket-admin#6]
PHP8.2
Nginx 1.24.0
thinkphp 8.0
安装完成之后提示 
Driver [Think] not supported.
    {
        if ($this->namespace || str_contains($type, '\\')) {
            $class = str_contains($type, '\\') ? $type : $this->namespace . Str::studly($type);

            if (class_exists($class)) {
                return $class;
            }
        }

        throw new InvalidArgumentException("Driver [$type] not supported.");
    }

    /**
     * 获取驱动参数
     * @param $name
     * @return array
     */
    protected function resolveParams($name): array

**Comment by deatil** [comment]
看下报错栈，能确认下是哪个用驱动报错的

**Comment by deatil** [comment]
看下报错栈，能确认下是哪个位置开始报错的吗？

**Comment by deatil** [comment]
新提交版本已经修复了
