### ISSUE TITLE
Template.php第 793 行出现错误 未找到类“\Laket\Admin\View\Laket\TagLib\Cx”

### ISSUE THREAD

**Issue by vpscn2gmail** [deatil/laket-admin#7]
宝塔面板
PHP 8.0
Nginx 1.24.0
Composer版本2.2.4

报错
Class "\Laket\Admin\View\Laket\TagLib\Cx" not found
    {
        if (str_contains($tagLib, '\\')) {
            // 支持指定标签库的命名空间
            $className = $tagLib;
            $tagLib    = substr($tagLib, strrpos($tagLib, '\\') + 1);
        } else {
            $className = '\\Laket\\Admin\\View\\Laket\\TagLib\\' . ucwords($tagLib);
        }

        $tLib = new $className($this);

        $tLib->parseTag($content, $hide ? '' : $tagLib);
    }

    /**
     * 分析标签属性
     * @access public
     * @param string      $str  属性字符串
     * @param string|null $name 不为空时返回指定的属性名

**Comment by deatil** [comment]
新提及版本修复了这个问题
