### ISSUE TITLE
请问后台验证码一直错误是什么情况,也输入正确了

### ISSUE THREAD

**Issue by liyang042218** [deatil/laket-admin#8]
请问后台验证码一直错误是什么情况,也输入正确了

**Comment by deatil** [comment]
验证码用的是官方的库，你可以先看下有没有报错日志

**Comment by liyang042218** [comment]
$adminInfo = Admin::login($data['name'], $password);
        if (empty($adminInfo)) {
            do_action('admin_passport_login_check_password_error');
            
            return $this->error('用户名或者密码错误！');
        }
这个Admin::的login函数是不是没有这个方法啊，作者

**Comment by deatil** [comment]
有这个方法。
是有报错吗？报的什么错

**Comment by liyang042218** [comment]
![捕获](https://github.com/user-attachments/assets/6362fb44-a019-41ad-a131-d4cbe41bb59d)
验证码能正常显示 其他的也没有报错  验证码插件也有  但就是验证码一直错误 php8.0

**Comment by liyang042218** [comment]
账号是admin和123456吧

**Comment by liyang042218** [comment]
![捕获](https://github.com/user-attachments/assets/350567ef-5480-4e3f-b2dd-c367633cdc8d)
qin请求200成功了但是 还是提示验证码错误

**Comment by deatil** [comment]
验证码跟cookie有关，遇到过浏览器的问题会失败，可以换个浏览器看下还有没有问题

**Comment by deatil** [comment]
访问用的是本地对应的域名还是ip，是ip的话用host设置一个域名试下

**Comment by liyang042218** [comment]
用的就是虚拟域名还是不行

**Comment by liyang042218** [comment]
在您的本地能跑起来吗

**Comment by deatil** [comment]
> 在您的本地能跑起来吗

能。验证码不能通过，大概率跟官方的验证码库有关，你可以单独的开个项目测试下验证码

**Comment by liyang042218** [comment]
您能，把您本地的库文件能直接也上传到仓库吗，昨天我把所有包都删除了又重新composer update了一下，还是不行

**Comment by deatil** [comment]
可以用 composer.lock 文件install 看看有没有问题。有问题估计就是浏览器问题了
https://github.com/deatil/laket-admin/blob/main/docs/composer.lock.txt

**Comment by deatil** [comment]
复制文件内容到lock文件
